region: ap-northeast-1
cluster: gymlog-sys-prod-gymlog-app
service: gymlog-sys-prod-gymlog-app
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 10m0s
plugins:
  - name: tfstate
    config:
      url: s3://pplmtv-tfstate/gymlog-sys/prod/cicd/gymlog-app_v1.0.0.tfstate
